import streamlit as st

st.write("物理基礎の公式:")
st.latex(r'\bar{v}=\frac{\Delta x}{\Delta t}')
st.latex(r'\bar{v}=\frac{x_2-x_1}{t_2-t_1}=\frac{\Delta x}{\Delta t}')
st.latex(r'x=vt')
st.latex(r'\vec{v}=\vec{v_1}+\vec{v_2}')
st.latex(r'\vec{v_(ab)}=\vec{v_b}-\vec{v_a}')
st.latex(r'a=\frac{x_2-x_1}{t_2-t_1}')
st.latex(r'v=v_o+at')
st.latex(r'x=v_ot+\frac{1}{2}at^2')
st.latex(r'v^2-v_o^2=2ax')
st.latex(r'v=gt')
st.latex(r'y=\frac{1}{2}gt^2')
st.latex(r'v^2=2gy')
st.latex(r'v=v_o+gt')
st.latex(r'y=v_ot+\frac{1}{2}gt^2')
st.latex(r'v^2-v_o^2=2gy')
st.latex(r'v=v_o-gt')
st.latex(r'y=v_o-\frac{1}{2}gt^2')
st.latex(r'v^2-v_o^2=-agy')
st.latex(r'x=v_ot')
st.latex(r'y=\frac{1}{2}gt^2')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')