import streamlit as st

st.write("物理基礎の公式:")
st.latex(r'\bar{v}=\frac{\Delta x}{\Delta t}')
st.latex(r'\bar{v}=\frac{x_2-x_1}{t_2-t_1}=\frac{\Delta x}{\Delta t}')
st.write(r'x=vt')
st.latex(r'\vec{V}=\vec{v_1}+\vec{v_2}')
st.latex(r'\vec{V_ab}=\vec{v_b}-\vec{v_a}')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')
st.latex(r'')